import type { Metadata } from "next";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  fleet,
}: Readonly<{
  children: React.ReactNode;
  fleet: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/neue-haas-grotesk-display-pro"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="max-w-[1512px] mx-auto">
          <Header />
          <main className="flex-1 px-[20px] md:px-[80px]">{children}</main>
          {fleet}
        </div>
        <div className="border-t-2 border-[#787878]">
          <div className="max-w-[1512px] mx-auto pt-[80px]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
